// Mocks generated by Mockito 5.0.12 from annotations
// in officium_flutter/test/infraestructura/contrataciones/postulaciones/repositorios/postulacion_repositorio_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:officium_flutter/infraestructura/contrataciones/oferta_laboral/modelos/postulacion_oferta_laboral_dto.dart'
    as _i5;
import 'package:officium_flutter/infraestructura/contrataciones/postulacion/fuentes/i_postulacion_fuente.dart'
    as _i3;
import 'package:officium_flutter/infraestructura/contrataciones/postulacion/modelos/postulacion_empleado_dto.dart'
    as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUnit extends _i1.Fake implements _i2.Unit {}

/// A class which mocks [IPostulacionFuente].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPostulacionFuente extends _i1.Mock
    implements _i3.IPostulacionFuente {
  MockIPostulacionFuente() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Unit> aplicarOfertaLaboral(
          _i5.PostulacionOfertaLaboralDTO? postulacionOfertaLaboral) =>
      (super.noSuchMethod(
          Invocation.method(#aplicarOfertaLaboral, [postulacionOfertaLaboral]),
          returnValue:
              Future<_i2.Unit>.value(_FakeUnit())) as _i4.Future<_i2.Unit>);
  @override
  _i4.Future<List<_i6.PostulacionEmpleadoDTO>>
      obtenerPostulacionesActivasEmpleado(String? uuidEmpleado) =>
          (super.noSuchMethod(
                  Invocation.method(
                      #obtenerPostulacionesActivasEmpleado, [uuidEmpleado]),
                  returnValue: Future<List<_i6.PostulacionEmpleadoDTO>>.value(
                      <_i6.PostulacionEmpleadoDTO>[]))
              as _i4.Future<List<_i6.PostulacionEmpleadoDTO>>);
  @override
  _i4.Future<_i2.Unit> cancelarPostulacion(String? uuidPostulacion) =>
      (super.noSuchMethod(
              Invocation.method(#cancelarPostulacion, [uuidPostulacion]),
              returnValue: Future<_i2.Unit>.value(_FakeUnit()))
          as _i4.Future<_i2.Unit>);
}
